sudo: false
language: node_js
cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules
node_js:
  - '6'
before_install:
  - time npm i yarn ---cache-min 99999999
install:
  - ./node_modules/.bin/yarn
script:
  - npm test
branches:
  only:
    - master
    - dev
